version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uts_server_app
    working_dir: /var/www/uts_server
    volumes:
      - ./:/var/www/uts_server
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=uts_server_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - uts_server_network

  db:
    image: mysql:8.0
    container_name: uts_server_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=uts_server_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - uts_server_network

volumes:
  db_data:

networks:
  uts_server_network:
    driver: bridge